services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks-raw
    restart: always
    network_mode: "host"
    environment:
      - SERVER_PORT=${SERVER_PORT:-24000}
      - SERVER_ADDR=127.0.0.1
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=HELLOWORLD

  # JP FRP server
  frpc-jp:
    image: fatedier/frpc:v0.63.0
    container_name: frpc-jp
    restart: always
    network_mode: "host"
    environment:
      - FRP_SERVER_ADDR=${FRP_JP_SERVER_ADDR:-103.0.0.0}
      - FRP_SERVER_PORT=${FRP_JP_SERVER_PORT:-7200}
      - FRP_AUTH_TOKEN=${FRP_JP_AUTH_TOKEN:-helloworld}
      - SERVER_PORT=${SERVER_PORT:-24000}
      - FRP_REMOTE_PORT=${FRP_REMOTE_PORT:-50000}
    volumes:
      - ./frpc-jp.toml:/etc/frp/frpc.toml
    command: ["-c", "/etc/frp/frpc.toml"]
    depends_on:
      - shadowsocks

  # HK FRP server
  frpc-hk:
    image: fatedier/frpc:v0.63.0
    container_name: frpc-hk
    restart: always
    network_mode: "host"
    environment:
      - FRP_SERVER_ADDR=${FRP_HK_SERVER_ADDR:-103.0.0.0}
      - FRP_SERVER_PORT=${FRP_HK_SERVER_PORT:-7200}
      - FRP_AUTH_TOKEN=${FRP_HK_AUTH_TOKEN:-helloworld}
      - SERVER_PORT=${SERVER_PORT:-24000}
      - FRP_REMOTE_PORT=${FRP_REMOTE_PORT:-50000}
    volumes:
      - ./frpc-hk.toml:/etc/frp/frpc.toml
    command: ["-c", "/etc/frp/frpc.toml"]
    depends_on:
      - shadowsocks