serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

[[proxies]]
name = "shadowsocks-asia-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = {{ .Envs.SS_LOCAL_PORT }}
remotePort = {{ .Envs.FRP_REMOTE_PORT }}

[[proxies]]
name = "shadowsocks-asia-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = {{ .Envs.SS_LOCAL_PORT }}
remotePort = {{ .Envs.FRP_REMOTE_PORT }}